#!/bin/sh
brew cask install 1password
brew cask install a-better-finder-rename
brew cask install bbedit
brew cask install bettertouchtool
brew cask install candybar
brew cask install coda
brew cask install colorschemer-studio
brew cask install delicious-library
brew cask install disk-inventory-x
brew cask install firefox
brew cask install fluid
brew cask install google-chrome
brew cask install handbrake
brew cask install hazel
brew cask install hyperdock
brew cask install identify
brew cask install istat-menus
brew cask install iexplorer
brew cask install igetter
brew cask install imageoptim
brew cask install makemkv
brew cask install silverlight
brew cask install mindnode-pro
brew cask install navicat-for-mysql
brew cask install omnifocus
brew cask install omnigraffle
brew cask install omnioutliner
brew cask install paparazzi
brew cask install parallels-desktop
brew cask install path-finder
brew cask install pdfpenpro
brew cask install quicksilver
brew cask install sequel-pro
brew cask install skype
brew cask install softraid
brew cask install soulver
brew cask install superduper
brew cask install totalspaces
brew cask install tower
brew cask install transmission
brew cask install transmit
brew cask install vlc
